db2700: schema.c File Reference
schema.c File Reference
#include "schema.h"
#include "pmsg.h"
#include <string.h>
Data Structures
struct field_desc_struct
Field descriptor.
struct schema_struct
Table/record schema.
struct tbl_desc_struct
Table descriptor.
Typedefs
typedef struct field_desc_struct field_desc_struct
Field descriptor.
typedef struct schema_struct schema_struct
Table/record schema.
typedef struct tbl_desc_struct tbl_desc_struct
Table descriptor.
Functions
void put_field_info (pmsg_level level, field_desc_p f)
void put_schema_info (pmsg_level level, schema_p s)
void put_tbl_info (pmsg_level level, tbl_p t)
void put_record_info (pmsg_level level, record r, schema_p s)
void put_db_info (pmsg_level level)
field_desc_p new_int_field (char const *name)
field_desc_p new_str_field (char const *name, int len)
int is_int_field (field_desc_p f)
field_desc_p field_desc_next (field_desc_p f)
char const *const schema_name (schema_p sch)
field_desc_p schema_first_fld_desc (schema_p sch)
field_desc_p schema_last_fld_desc (schema_p sch)
int schema_num_flds (schema_p sch)
int schema_len (schema_p sch)
int open_db (void)
void close_db (void)
schema_p new_schema (char const *name)
tbl_p get_table (char const *name)
schema_p get_schema (char const *name)
void remove_table (tbl_p t)
void remove_schema (schema_p s)
int add_field (schema_p s, field_desc_p f)
record new_record (schema_p s)
void release_record (record r, schema_p s)
void assign_int_field (void const *field_p, int int_val)
void assign_str_field (void *field_p, char const *str_val)
int fill_record (record r, schema_p s,...)
int equal_record (record r1, record r2, schema_p s)
void set_tbl_position (tbl_p t, tbl_position pos)
int eot (tbl_p t)
int get_record (record r, schema_p s)
int put_record (record r, schema_p s)
void append_record (record r, schema_p s)
void table_display (tbl_p t)
tbl_p table_search (tbl_p t, char const *attr, char const *op, int val)
tbl_p table_project (tbl_p t, int num_fields, char *fields[])
tbl_p table_natural_join (tbl_p left, tbl_p right)
Variables
tbl_p db_tables
Database tables.
const char tables_desc_file [] = "db.db"
Typedef Documentation
field_desc_struct
typedef struct field_desc_struct field_desc_struct
Field descriptor.
schema_struct
typedef struct schema_struct schema_struct
Table/record schema.
A schema is a linked list of field descriptors. All records of a table are of the same length.
tbl_desc_struct
typedef struct tbl_desc_struct tbl_desc_struct
Table descriptor.
A table descriptor allows us to find the schema and run-time infomation about the table.
Function Documentation
add_field()
int add_field (schema_p s, field_desc_p f)
Add a field to the schema
Definition at line 417 of file schema.c.
References BLOCK_SIZE, ERROR, schema_struct::first, schema_struct::last, field_desc_struct::len, schema_struct::len, field_desc_struct::next, schema_struct::num_fields, field_desc_struct::offset, PAGE_HEADER_SIZE, and put_msg().
Referenced by create_test_schema().
append_record()
void append_record (record const r, schema_p s)
Append the record to the table file. The current position moves to the new end of the file.
Definition at line 667 of file schema.c.
References FATAL, get_page_for_append(), schema_struct::name, put_msg(), and schema_struct::tbl.
Referenced by test_tbl_write().
assign_int_field()
void assign_int_field (void const * field_p, int int_val)
Assign an int record field. Note the data type of field_pp
Definition at line 466 of file schema.c.
Referenced by fill_record().
assign_str_field()
void assign_str_field (void * field_p, char const * str_val)
Assign a str record field. Note the data type of field_pp
Definition at line 470 of file schema.c.
Referenced by fill_record().
close_db()
void close_db (void)
Close a database
Definition at line 305 of file schema.c.
Referenced by test_tbl_natural_join(), test_tbl_read(), and test_tbl_write().
eot()
int eot (tbl_p t)
Whether the current position is at end of table.
Definition at line 542 of file schema.c.
References tbl_desc_struct::current_pg, and peof().
Referenced by test_tbl_read().
equal_record()
int equal_record (record const r1, record const r2, schema_p s)
Compare if two records have equal field values
Definition at line 508 of file schema.c.
References ERROR, schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by test_tbl_read().
field_desc_next()
field_desc_p field_desc_next (field_desc_p f)
Returns the next field_desc
Definition at line 147 of file schema.c.
References ERROR, field_desc_struct::next, and put_msg().
fill_record()
int fill_record (record const r, schema_p s, ...)
Fill a record with values. Example: fill_record(r, s, 1, "A string", 136)
Definition at line 474 of file schema.c.
References assign_int_field(), assign_str_field(), ERROR, schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by fill_gen_record().
get_record()
int get_record (record const r, schema_p s)
Retrieve the record value at the current position. The current position moves to the next record. Returns 1 when r is updated, 0 when there is no more record, and -1 when something goes wrong.
Definition at line 592 of file schema.c.
Referenced by test_tbl_read().
get_schema()
schema_p get_schema (char const * name)
Return an existing schema, NULL if the named schema does not exist.
Definition at line 329 of file schema.c.
References get_table(), and tbl_desc_struct::sch.
Referenced by create_test_schema(), and test_tbl_read().
get_table()
tbl_p get_table (char const * name)
Return an existing table desc, NULL if the table does not exist.
Definition at line 322 of file schema.c.
References db_tables, schema_struct::name, tbl_desc_struct::next, and tbl_desc_struct::sch.
Referenced by get_schema(), test_tbl_natural_join(), and test_tbl_read().
is_int_field()
int is_int_field (field_desc_p f)
Check if this is an int field. Since there are only int and str fields, "not int" means str.
Definition at line 143 of file schema.c.
References INT_TYPE, and field_desc_struct::type.
Referenced by equal_record(), fill_record(), put_field_info(), and put_record_info().
new_int_field()
field_desc_p new_int_field (char const * name)
Make an int field with name name.
Definition at line 115 of file schema.c.
References INT_SIZE, INT_TYPE, field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, and field_desc_struct::type.
Referenced by create_test_schema().
new_record()
record new_record (schema_p s)
Creates a new record of schema s. It is the responsibility of the using program to free the memory of the resulting record using release_record().
Definition at line 439 of file schema.c.
References ERROR, schema_struct::first, field_desc_struct::len, field_desc_struct::next, schema_struct::num_fields, and put_msg().
Referenced by test_data_gen(), and test_tbl_read().
new_schema()
schema_p new_schema (char const * name)
Make a new schema and add it to the current database
Definition at line 311 of file schema.c.
References tbl_desc_struct::sch.
Referenced by create_test_schema().
new_str_field()
field_desc_p new_str_field (char const * name, int len)
Make an string field with name name and length len.
Definition at line 125 of file schema.c.
References field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, STR_TYPE, and field_desc_struct::type.
Referenced by create_test_schema().
open_db()
int open_db (void)
Open a database that was created in a previous session. The database and tables are stored at sys_dir. Return 0 upon failure.
Definition at line 298 of file schema.c.
References pager_init(), and pager_terminate().
Referenced by test_tbl_natural_join(), test_tbl_read(), and test_tbl_write().
put_db_info()
void put_db_info (pmsg_level level)
Definition at line 106 of file schema.c.
References db_tables, tbl_desc_struct::next, put_msg(), put_tbl_info(), and system_dir().
Referenced by test_tbl_natural_join(), and test_tbl_write().
put_field_info()
void put_field_info (pmsg_level level, field_desc_p f)
Definition at line 48 of file schema.c.
References append_msg(), is_int_field(), field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, and put_msg().
Referenced by put_schema_info().
put_record()
int put_record (record const r, schema_p s)
Put the record value at the current position. The current position moves to the next record. Returns -1 if there is not enough space at current position.
Definition at line 650 of file schema.c.
References tbl_desc_struct::current_pg, and schema_struct::tbl.
put_record_info()
void put_record_info (pmsg_level level, record r, schema_p s)
Definition at line 90 of file schema.c.
References append_msg(), schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by test_tbl_read().
put_schema_info()
void put_schema_info (pmsg_level level, schema_p s)
Definition at line 65 of file schema.c.
References schema_struct::first, schema_struct::len, schema_struct::name, field_desc_struct::next, schema_struct::num_fields, put_field_info(), and put_msg().
Referenced by create_test_schema(), and put_tbl_info().
put_tbl_info()
void put_tbl_info (pmsg_level level, tbl_p t)
Definition at line 78 of file schema.c.
References file_num_blocks(), schema_struct::name, tbl_desc_struct::num_records, put_file_info(), put_msg(), put_schema_info(), and tbl_desc_struct::sch.
Referenced by put_db_info().
release_record()
void release_record (record r, schema_p s)
Release the memory allocated for the record and its fields.
Definition at line 455 of file schema.c.
References ERROR, schema_struct::num_fields, and put_msg().
Referenced by test_tbl_read().
remove_schema()
void remove_schema (schema_p s)
Remove a schema from the current database
Definition at line 357 of file schema.c.
References remove_table(), and schema_struct::tbl.
Referenced by create_test_schema().
remove_table()
void remove_table (tbl_p t)
Remove a table from the current database
Definition at line 335 of file schema.c.
References close_file(), db_tables, schema_struct::name, tbl_desc_struct::next, and tbl_desc_struct::sch.
Referenced by remove_schema().
schema_first_fld_desc()
field_desc_p schema_first_fld_desc (schema_p sch)
Return the first field_desc of schema.
Definition at line 190 of file schema.c.
References ERROR, schema_struct::first, and put_msg().
schema_last_fld_desc()
field_desc_p schema_last_fld_desc (schema_p sch)
Return the last field_desc of schema.
Definition at line 199 of file schema.c.
References ERROR, schema_struct::last, and put_msg().
schema_len()
int schema_len (schema_p sch)
Return length of schema in number of bytes.
Definition at line 217 of file schema.c.
References ERROR, schema_struct::len, and put_msg().
schema_name()
char const *const schema_name (schema_p sch)
Return name of schema.
Definition at line 181 of file schema.c.
References ERROR, schema_struct::name, and put_msg().
Referenced by fill_gen_record().
schema_num_flds()
int schema_num_flds (schema_p sch)
Return number of fields in schema.
Definition at line 208 of file schema.c.
References ERROR, schema_struct::num_fields, and put_msg().
set_tbl_position()
void set_tbl_position (tbl_p t, tbl_position pos)
Set the current position to the beginning or end of the table.
Definition at line 529 of file schema.c.
References tbl_desc_struct::current_pg, get_page(), get_page_for_append(), schema_struct::name, page_set_pos_begin(), tbl_desc_struct::sch, TBL_BEG, and TBL_END.
Referenced by test_tbl_read().
table_display()
void table_display (tbl_p s)
Print all rows of a table.
Definition at line 723 of file schema.c.
table_natural_join()
tbl_p table_natural_join (tbl_p left, tbl_p right)
Join two tables and return the joined table.
Definition at line 818 of file schema.c.
References ERROR, and put_msg().
Referenced by test_tbl_natural_join().
table_project()
tbl_p table_project (tbl_p t, int num_fields, char * fields[])
Make a new table as a result of project.
Definition at line 798 of file schema.c.
References tbl_desc_struct::sch.
table_search()
tbl_p table_search (tbl_p t, char const * attr, char const * op, int val)
Make a new table as the result of a search.
Definition at line 739 of file schema.c.
Variable Documentation
db_tables
tbl_p db_tables
Database tables.
a linked list of table descriptors
Definition at line 46 of file schema.c.
Referenced by get_table(), put_db_info(), and remove_table().
tables_desc_file
const char tables_desc_file[] = "db.db"
Definition at line 226 of file schema.c.