db2700: testpager.c File Reference
testpager.c File Reference
#include "testpager.h"
#include "pmsg.h"
#include <string.h>
Macros
#define NUM_BLOCKS_IN_FILE 20 /* can be greater than NUM_PAGES */
#define NUM_RECORDS_IN_BLOCK 3
Functions
void test_page_write (char const *fname)
void test_page_read (char const *fname)
void test_page_write_with_offset (char const *fname)
void test_page_read_with_offset (char const *fname)
Macro Definition Documentation
NUM_BLOCKS_IN_FILE
#define NUM_BLOCKS_IN_FILE 20 /* can be greater than NUM_PAGES */
Definition at line 5 of file testpager.c.
NUM_RECORDS_IN_BLOCK
#define NUM_RECORDS_IN_BLOCK 3
Definition at line 6 of file testpager.c.
Function Documentation
test_page_read()
void test_page_read (char const * fname)
Definition at line 50 of file testpager.c.
References eop(), FATAL, get_page(), INFO, NUM_BLOCKS_IN_FILE, page_get_int(), pager_init(), put_msg(), and put_pager_info().
test_page_read_with_offset()
void test_page_read_with_offset (char const * fname)
Definition at line 134 of file testpager.c.
References eop(), FATAL, get_page(), INFO, INT_SIZE, NUM_BLOCKS_IN_FILE, PAGE_HEADER_SIZE, pager_init(), put_msg(), and put_pager_info().
test_page_write()
void test_page_write (char const * fname)
Definition at line 12 of file testpager.c.
References FATAL, get_page(), INFO, NUM_BLOCKS_IN_FILE, NUM_RECORDS_IN_BLOCK, page_put_int(), pager_init(), put_msg(), and put_pager_info().
test_page_write_with_offset()
void test_page_write_with_offset (char const * fname)
Definition at line 98 of file testpager.c.
References FATAL, get_page(), INFO, INT_SIZE, NUM_BLOCKS_IN_FILE, NUM_RECORDS_IN_BLOCK, PAGE_HEADER_SIZE, pager_init(), put_msg(), and put_pager_info().