db2700: testschema.c File Reference
testschema.c File Reference
#include <string.h>
#include "testschema.h"
#include "test_data_gen.h"
#include "pmsg.h"
Macros
#define NUM_RECORDS 1000
Functions
void test_tbl_write (char const *tbl_name)
void test_tbl_read (char const *tbl_name)
void test_tbl_natural_join (char const *my_tbl, char const *yr_tbl)
Variables
record in_recs [NUM_RECORDS]
Macro Definition Documentation
NUM_RECORDS
#define NUM_RECORDS 1000
Definition at line 6 of file testschema.c.
Function Documentation
test_tbl_natural_join()
void test_tbl_natural_join (char const * my_tbl, char const * yr_tbl)
Definition at line 80 of file testschema.c.
References close_db(), DEBUG, get_table(), INFO, open_db(), put_db_info(), put_msg(), put_pager_profiler_info(), table_natural_join(), and test_tbl_write().
Referenced by main().
test_tbl_read()
void test_tbl_read (char const * tbl_name)
Definition at line 41 of file testschema.c.
References close_db(), eot(), equal_record(), ERROR, FATAL, get_record(), get_schema(), get_table(), in_recs, INFO, new_record(), NUM_RECORDS, open_db(), put_msg(), put_pager_profiler_info(), put_record_info(), release_record(), set_tbl_position(), and TBL_BEG.
Referenced by main().
test_tbl_write()
void test_tbl_write (char const * tbl_name)
Definition at line 13 of file testschema.c.
References append_record(), close_db(), create_test_schema(), DEBUG, in_recs, INFO, INT_TYPE, NUM_RECORDS, open_db(), put_db_info(), put_msg(), put_pager_profiler_info(), STR_TYPE, and test_data_gen().
Referenced by main(), and test_tbl_natural_join().
Variable Documentation
in_recs
record in_recs[NUM_RECORDS]
Definition at line 10 of file testschema.c.
Referenced by test_tbl_read(), and test_tbl_write().