db2700: test_data_gen.h File Reference
test_data_gen.h File Reference
Test data generator.
#include "schema.h"
Functions
schema_p create_test_schema (char const *name, int n_attrs, char *attrs[], int attr_types[])
void prepare_test_data_gen ()
void test_data_gen (schema_p sch, record *r, int n)
void fill_gen_record (schema_p s, record r, int id)
Detailed Description
Test data generator.
Author
Weihai Yu
Definition in file test_data_gen.h.
Function Documentation
create_test_schema()
schema_p create_test_schema (char const * name, int n_attrs, char * attrs[], int attr_types[])
create the test schema my_schema (MyIdField: int, MyStrField:str[TEST_STR_LEN], myIntField:int)
Definition at line 7 of file test_data_gen.c.
References add_field(), DEBUG, ERROR, get_schema(), INT_TYPE, new_int_field(), new_schema(), new_str_field(), put_msg(), put_schema_info(), remove_schema(), STR_TYPE, and TEST_STR_LEN.
Referenced by test_tbl_write().
fill_gen_record()
void fill_gen_record (schema_p s, record r, int id)
fill a record with some generated data.
values (id, schema_Val_id, rand())
Definition at line 45 of file test_data_gen.c.
References fill_record(), schema_name(), and TEST_STR_LEN.
Referenced by test_data_gen().
prepare_test_data_gen()
void prepare_test_data_gen ()
prepare the test data generator. For each run, the same series of random numbers are generated
Definition at line 30 of file test_data_gen.c.
Referenced by main().
test_data_gen()
void test_data_gen (schema_p sch, record * r, int n)
resets the test data generator. next_test_record_id is set to 0
Definition at line 35 of file test_data_gen.c.
References fill_gen_record(), and new_record().
Referenced by test_tbl_write().